In [2]:
import numpy as np
import matplotlib.pyplot as plt

| Size (sqft) | Number of Bedrooms  | Number of floors | Age of  Home | Price (1000s dollars)  |   
| ----------------| ------------------- |----------------- |--------------|-------------- |  
| 2104            | 5                   | 1                | 45           | 460           |  
| 1416            | 3                   | 2                | 40           | 232           |  
| 852             | 2                   | 1                | 35           | 178           |  

In [3]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

print(f"X shape : {X_train.shape}, X Type : {type(X_train)}")
print(X_train)
print(f"Y shape : {y_train.shape}, Y Type : {type(y_train)}")
print(y_train)


b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"W shape : {w_init.shape}, W Type : {type(w_init)}")

X shape : (3, 4), X Type : <class 'numpy.ndarray'>
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
Y shape : (3,), Y Type : <class 'numpy.ndarray'>
[460 232 178]
W shape : (4,), W Type : <class 'numpy.ndarray'>


In [ ]:
def predict(x,w,b):
    p = np.dot(x,w) + b
    return p
    
def gradient(x,y,w,b):
    m = x.shape[0]
    for i in range(m):


SyntaxError: expected '(' (2627427683.py, line 4)